# Generated by Django 5.0.6 on 2026-07-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_gin_search_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='churchevent',
            options={'managed': True},
        ),
    ]
