# Generated by Django 5.2.16 on 2026-07-21 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('events', '0003_alter_churchevent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='createdById', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_events', to='accounts.user'),
        ),
        migrations.AddIndex(
            model_name='churchevent',
            index=models.Index(fields=['start_date_time'], name='event_start_idx'),
        ),
        migrations.AddIndex(
            model_name='churchevent',
            index=models.Index(fields=['status'], name='event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='churchevent',
            index=models.Index(fields=['type'], name='event_type_idx'),
        ),
    ]
