# Generated by Django 5.2.16 on 2026-07-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_churchevent_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventregistration',
            options={'managed': True},
        ),
    ]
