# Generated by Django 5.2.16 on 2026-07-21
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventregistration_options'),
        ('content', '0007_reconcile_content_indexes'),
        ('members', '__first__'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='eventregistration',
                    name='event',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        db_column='eventId',
                        db_constraint=False,
                        related_name='registrations',
                        to='events.churchevent',
                    ),
                ),
                migrations.AddField(
                    model_name='eventregistration',
                    name='member',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        db_column='memberId',
                        db_constraint=False,
                        related_name='event_registrations',
                        to='members.member',
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['registration_date'], name='reg_regdate_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['event'], name='reg_event_idx'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['member'], name='reg_member_idx'),
        ),
    ]