"""Convert TEXT primary key columns to UUID type for Prisma-legacy tables.

All existing UUID values stored as TEXT have been validated as valid UUIDs.
This migration alters the column types to match Django model declarations.

FK constraints are dropped before conversion and not recreated because all Django 
ForeignKey declarations use db_constraint=False (no DB-level enforcement).

Generated by manual audit (B4.2.4). Not auto-generated by makemigrations.
"""

from django.db import migrations


class Migration(migrations.Migration):
    """Convert TEXT id columns to UUID for Prisma-legacy tables in events app."""

    dependencies = [
        ('events', '0006_reconcile_eventregistration_fields'),
    ]

    operations = [
        # Drop FK constraints that would block column type conversion
        migrations.RunSQL(
            sql="""
            ALTER TABLE "EventRegistration" DROP CONSTRAINT IF EXISTS "EventRegistration_eventId_fkey";
            ALTER TABLE "EventRegistration" DROP CONSTRAINT IF EXISTS "EventRegistration_memberId_fkey";
            ALTER TABLE "ChurchEvent" DROP CONSTRAINT IF EXISTS "ChurchEvent_createdById_fkey";
            """,
            reverse_sql="",
        ),
        # Convert pk columns
        migrations.RunSQL(
            sql="""
            ALTER TABLE "ChurchEvent" ALTER COLUMN id TYPE uuid USING id::uuid;
            ALTER TABLE "EventRegistration" ALTER COLUMN id TYPE uuid USING id::uuid;
            """,
            reverse_sql="""
            ALTER TABLE "ChurchEvent" ALTER COLUMN id TYPE text;
            ALTER TABLE "EventRegistration" ALTER COLUMN id TYPE text;
            """,
            state_operations=None,
        ),
    ]