# Generated by Django 5.0.6 on 2026-07-30 19:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGE', 'Password Change'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('MEMBER_CREATE', 'Member Create'), ('MEMBER_UPDATE', 'Member Update'), ('MEMBER_DELETE', 'Member Delete'), ('MEMBER_RESTORE', 'Member Restore'), ('HOUSEHOLD_CREATE', 'Household Create'), ('HOUSEHOLD_UPDATE', 'Household Update'), ('ATTENDANCE_CHECKIN', 'Attendance Check-in'), ('SESSION_OPEN', 'Session Open'), ('SESSION_CLOSE', 'Session Close'), ('GIVING_RECORD', 'Giving Record'), ('GIVING_UPDATE', 'Giving Update'), ('GIVING_DELETE', 'Giving Delete'), ('FUND_CREATE', 'Fund Create'), ('FUND_UPDATE', 'Fund Update'), ('EVENT_CREATE', 'Event Create'), ('EVENT_UPDATE', 'Event Update'), ('EVENT_DELETE', 'Event Delete'), ('ANNOUNCEMENT_CREATE', 'Announcement Create'), ('ANNOUNCEMENT_UPDATE', 'Announcement Update'), ('ROLE_ASSIGN', 'Role Assign'), ('USER_INVITE', 'User Invite'), ('USER_ACTIVATE', 'User Activate'), ('USER_DEACTIVATE', 'User Deactivate'), ('SETTINGS_CHANGE', 'Settings Change'), ('EXPORT_DATA', 'Export Data'), ('IMPORT_DATA', 'Import Data'), ('CONSENT_COLLECTED', 'Consent Collected'), ('CARE_CASE_CREATE', 'Care Case Create'), ('CARE_CASE_UPDATE', 'Care Case Update'), ('CARE_NOTE_CREATE', 'Care Note Create'), ('VOLUNTEER_ASSIGN', 'Volunteer Assign'), ('PRAYER_REQUEST_CREATE', 'Prayer Request Create'), ('PRAYER_REQUEST_ANSWERED', 'Prayer Request Answered'), ('COMMUNICATION_SENT', 'Communication Sent')], max_length=40)),
                ('entity_type', models.CharField(db_column='entityType', max_length=100)),
                ('entity_id', models.CharField(blank=True, db_column='entityId', max_length=255, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, db_column='ipAddress', max_length=64, null=True)),
                ('user_agent', models.CharField(blank=True, db_column='userAgent', max_length=512, null=True)),
                ('timestamp', models.DateTimeField(db_column='timestamp')),
            ],
            options={
                'db_table': 'AuditLog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(db_column='passwordHash', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('HOSPITALITY', 'Hospitality'), ('LEADERSHIP', 'Leadership'), ('CELL_LEADER', 'Cell Leader'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('must_change_password', models.BooleanField(db_column='mustChangePassword', default=True)),
                ('failed_login_attempts', models.IntegerField(db_column='failedLoginAttempts', default=0)),
                ('locked_until', models.DateTimeField(blank=True, db_column='lockedUntil', null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='lastLogin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
                'managed': True,
                'indexes': [models.Index(fields=['role'], name='user_role_idx')],
            },
        ),
    ]
