# Generated by Django for GIN search indexes - B2.3B
# This file adds PostgreSQL GIN indexes for full-text search on Django-owned models

from django.contrib.postgres.indexes import GinIndex
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        # GIN index for ContentBlock search (title=A, content=C)
        # Note: Weighted GIN indexes require RunSQL for expression-based indexes
        # Using standard GIN index on tsvector expression
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_contentblock_search
            ON content_contentblock
            USING GIN (
                (setweight(to_tsvector('simple', COALESCE(title, '')), 'A') ||
                 setweight(to_tsvector('simple', COALESCE(content, '')), 'C'))
            );
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_contentblock_search;",
        ),
        # GIN index for ChurchProfile search (mission=vision=welcome_message=pastor_message=about_text=C)
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS idx_churchprofile_search
            ON content_churchprofile
            USING GIN (
                (setweight(to_tsvector('simple', COALESCE(mission, '')), 'C') ||
                 setweight(to_tsvector('simple', COALESCE(vision, '')), 'C') ||
                 setweight(to_tsvector('simple', COALESCE(welcome_message, '')), 'C') ||
                 setweight(to_tsvector('simple', COALESCE(pastor_message, '')), 'C') ||
                 setweight(to_tsvector('simple', COALESCE(about_text, '')), 'C'))
            );
            """,
            reverse_sql="DROP INDEX IF EXISTS idx_churchprofile_search;",
        ),
    ]