# Generated by Django 5.0.6 on 2026-07-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_gin_search_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='sermonseries',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='visitrsvp',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='websiteacademymodule',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='websitetestimonial',
            options={'managed': True},
        ),
    ]
