# Generated by Django 5.0.6 on 2026-07-21 17:35
# Modified: Use IF NOT EXISTS for indexes that may already exist from Prisma schema

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_contactsubmission_options_and_more'),
    ]

    operations = [
        # Ownership conversion: managed=False -> managed=True
        migrations.AlterModelOptions(
            name='publicsermon',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'managed': True},
        ),
        # Create indexes with IF NOT EXISTS to avoid conflicts with Prisma-created indexes
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "contactsub_creat_idx" ON "ContactSubmission" ("createdAt");',
            reverse_sql='DROP INDEX IF EXISTS "contactsub_creat_idx";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "series_ispub_idx" ON "SermonSeries" ("isPublished");',
            reverse_sql='DROP INDEX IF EXISTS "series_ispub_idx";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "series_sort_idx" ON "SermonSeries" ("sortOrder");',
            reverse_sql='DROP INDEX IF EXISTS "series_sort_idx";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "rsvp_created_idx" ON "VisitRsvp" ("createdAt");',
            reverse_sql='DROP INDEX IF EXISTS "rsvp_created_idx";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "rsvp_status_idx" ON "VisitRsvp" ("status");',
            reverse_sql='DROP INDEX IF EXISTS "rsvp_status_idx";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "academy_sort_idx" ON "WebsiteAcademyModule" ("sortOrder");',
            reverse_sql='DROP INDEX IF EXISTS "academy_sort_idx";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "testi_sort_idx" ON "WebsiteTestimonial" ("sortOrder");',
            reverse_sql='DROP INDEX IF EXISTS "testi_sort_idx";',
        ),
    ]