# Generated by Django 5.2.16 on 2026-07-21 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '__first__'),
        ('content', '0004_alter_publicsermon_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicsermon',
            name='series',
            field=models.ForeignKey(blank=True, db_column='seriesId', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sermons', to='content.sermonseries'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updatedById', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_configs', to='accounts.user'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['created_at'], name='contactsub_creat_idx'),
        ),
        migrations.AddIndex(
            model_name='publicsermon',
            index=models.Index(fields=['series_slug'], name='sermon_serislug_idx'),
        ),
        migrations.AddIndex(
            model_name='publicsermon',
            index=models.Index(fields=['is_published'], name='sermon_ispub_idx'),
        ),
        migrations.AddIndex(
            model_name='publicsermon',
            index=models.Index(fields=['date'], name='sermon_date_idx'),
        ),
        migrations.AddIndex(
            model_name='sermonseries',
            index=models.Index(fields=['is_published'], name='series_ispub_idx'),
        ),
        migrations.AddIndex(
            model_name='sermonseries',
            index=models.Index(fields=['sort_order'], name='series_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='systemconfig',
            index=models.Index(fields=['key'], name='syscfg_key_idx'),
        ),
        migrations.AddIndex(
            model_name='visitrsvp',
            index=models.Index(fields=['created_at'], name='rsvp_created_idx'),
        ),
        migrations.AddIndex(
            model_name='visitrsvp',
            index=models.Index(fields=['status'], name='rsvp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='websiteacademymodule',
            index=models.Index(fields=['sort_order'], name='academy_sort_idx'),
        ),
        migrations.AddIndex(
            model_name='websitetestimonial',
            index=models.Index(fields=['sort_order'], name='testi_sort_idx'),
        ),
    ]
