# Generated by Django 5.2.16 on 2026-07-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_publicsermon_series_systemconfig_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiteleader',
            options={'managed': True},
        ),
    ]
