# Generated by Django 5.2.16 on 2026-07-21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_websiteleader_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='publicsermon',
            index=models.Index(fields=['series_slug'], name='sermon_serislug_idx'),
        ),
        migrations.AddIndex(
            model_name='publicsermon',
            index=models.Index(fields=['is_published'], name='sermon_ispub_idx'),
        ),
        migrations.AddIndex(
            model_name='publicsermon',
            index=models.Index(fields=['date'], name='sermon_date_idx'),
        ),
        migrations.AddIndex(
            model_name='systemconfig',
            index=models.Index(fields=['key'], name='syscfg_key_idx'),
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "PublicSermon_seriesId_959d1c5b" ON "PublicSermon" ("seriesId");',
            reverse_sql='DROP INDEX IF EXISTS "PublicSermon_seriesId_959d1c5b";',
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "SystemConfig_updatedById_b94f0d76" ON "SystemConfig" ("updatedById");',
            reverse_sql='DROP INDEX IF EXISTS "SystemConfig_updatedById_b94f0d76";',
        ),
    ]