"""Convert TEXT primary key columns to UUID type for Prisma-legacy tables.

All existing UUID values stored as TEXT have been validated as valid UUIDs.
This migration alters the column types to match Django model declarations.

FK constraints are temporarily dropped and not recreated because all Django 
ForeignKey declarations use db_constraint=False (no DB-level enforcement).

Generated by manual audit (B4.2.4). Not auto-generated by makemigrations.
"""

from django.db import migrations


# List of all FK constraints that reference tables being converted
FK_CONSTRAINTS = [
    '"PublicSermon_seriesId_fkey"',
    '"PublicSermon_updatedById_fkey"',
    '"SystemConfig_updatedById_fkey"',
    '"EventRegistration_eventId_fkey"',
    '"EventRegistration_memberId_fkey"',
    '"ChurchEvent_createdById_fkey"',
]


class Migration(migrations.Migration):
    """Convert TEXT id columns to UUID for all Prisma-legacy tables."""

    dependencies = [
        ('content', '0007_reconcile_content_indexes'),
    ]

    operations = [
        # Drop FK constraints that would block column type conversion
        migrations.RunSQL(
            sql="ALTER TABLE \"PublicSermon\" DROP CONSTRAINT IF EXISTS \"PublicSermon_seriesId_fkey\";",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE \"PublicSermon\" DROP CONSTRAINT IF EXISTS \"PublicSermon_updatedById_fkey\";",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE \"SystemConfig\" DROP CONSTRAINT IF EXISTS \"SystemConfig_updatedById_fkey\";",
            reverse_sql="",
        ),
        # Convert pk columns
        migrations.RunSQL(
            sql="""
            ALTER TABLE "SystemConfig" ALTER COLUMN id TYPE uuid USING id::uuid;
            ALTER TABLE "SermonSeries" ALTER COLUMN id TYPE uuid USING id::uuid;
            ALTER TABLE "PublicSermon" ALTER COLUMN id TYPE uuid USING id::uuid;
            ALTER TABLE "WebsiteLeader" ALTER COLUMN id TYPE uuid USING id::uuid;
            ALTER TABLE "WebsiteTestimonial" ALTER COLUMN id TYPE uuid USING id::uuid;
            ALTER TABLE "WebsiteAcademyModule" ALTER COLUMN id TYPE uuid USING id::uuid;
            ALTER TABLE "ContactSubmission" ALTER COLUMN id TYPE uuid USING id::uuid;
            ALTER TABLE "VisitRsvp" ALTER COLUMN id TYPE uuid USING id::uuid;
            """,
            reverse_sql="""
            ALTER TABLE "SystemConfig" ALTER COLUMN id TYPE text;
            ALTER TABLE "SermonSeries" ALTER COLUMN id TYPE text;
            ALTER TABLE "PublicSermon" ALTER COLUMN id TYPE text;
            ALTER TABLE "WebsiteLeader" ALTER COLUMN id TYPE text;
            ALTER TABLE "WebsiteTestimonial" ALTER COLUMN id TYPE text;
            ALTER TABLE "WebsiteAcademyModule" ALTER COLUMN id TYPE text;
            ALTER TABLE "ContactSubmission" ALTER COLUMN id TYPE text;
            ALTER TABLE "VisitRsvp" ALTER COLUMN id TYPE text;
            """,
            state_operations=None,
        ),
    ]