# Generated by Django 5.0.6 on 2026-07-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_homepagesettings_cta_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastorprofile',
            options={'managed': True, 'verbose_name': 'Pastor Profile', 'verbose_name_plural': 'Pastor Profiles'},
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='cta_secondary_button_text',
            field=models.CharField(blank=True, default='Watch a Sermon', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='cta_secondary_button_url',
            field=models.URLField(blank=True, default='/sermons', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='cta_title',
            field=models.CharField(blank=True, default="You're Invited", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pastorprofile',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='pastorprofile',
            index=models.Index(fields=['is_active'], name='pastor_active_idx'),
        ),
        migrations.AddIndex(
            model_name='pastorprofile',
            index=models.Index(fields=['display_order'], name='pastor_order_idx'),
        ),
        migrations.AddIndex(
            model_name='websiteleader',
            index=models.Index(fields=['sort_order'], name='leader_sort_idx'),
        ),
    ]
