# Generated by Django 5.2.16 on 2026-07-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_pastorprofile_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_secondary_cta_text',
            field=models.CharField(blank=True, default='Watch a Sermon', help_text='Secondary CTA button text', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_secondary_cta_url',
            field=models.URLField(blank=True, default='/sermons', help_text='Secondary CTA button URL', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_button_text',
            field=models.CharField(blank=True, default='Plan Your Visit', help_text='CTA primary button text', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_button_url',
            field=models.URLField(blank=True, default='/visit', help_text='CTA primary button URL', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_description',
            field=models.TextField(blank=True, help_text='CTA banner description text', null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_heading',
            field=models.CharField(blank=True, default='Join Us This Sunday', help_text='CTA banner heading', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_location',
            field=models.CharField(blank=True, default='Thika, Kenya', help_text='Church location for CTA banner', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_secondary_button_text',
            field=models.CharField(blank=True, default='Watch a Sermon', help_text='CTA secondary button text', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_secondary_button_url',
            field=models.URLField(blank=True, default='/sermons', help_text='CTA secondary button URL', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='cta_title',
            field=models.CharField(blank=True, default="You're Invited", help_text='CTA banner title', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_background_image',
            field=models.URLField(blank=True, help_text='URL or path to hero background image', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_cta_text',
            field=models.CharField(blank=True, help_text='Primary CTA button text', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_cta_url',
            field=models.URLField(blank=True, help_text='Primary CTA button URL', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_scripture',
            field=models.TextField(blank=True, help_text='Hero scripture verse text', null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_scripture_reference',
            field=models.CharField(blank=True, help_text='Scripture reference (e.g. 1 Peter 2:9)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Hero subtitle beneath the heading', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Main hero heading text', max_length=255, null=True),
        ),
    ]
