# Generated by Django 5.2.16 on 2026-07-27 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_homepagesettings_hero_secondary_cta_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.systemconfig',),
        ),
        migrations.CreateModel(
            name='HomepageLatestSermon',
            fields=[
            ],
            options={
                'verbose_name': 'Latest Sermon',
                'verbose_name_plural': 'Latest Sermon',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.publicsermon',),
        ),
    ]
