# Generated by Django 5.2.16 on 2026-09-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_add_homepage_latest_sermon_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('homepage', 'Home'), ('about', 'About'), ('events', 'Events'), ('visit', 'Visit'), ('sermons', 'Sermons'), ('series', 'Series'), ('give', 'Give'), ('prayer', 'Prayer'), ('contact', 'Contact')], default='homepage', max_length=32)),
                ('key', models.SlugField(help_text="Section identifier, e.g. 'hero' (registry-controlled)", max_length=64)),
                ('title', models.CharField(help_text='Admin label, e.g. "Hero Section"', max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Section',
                'verbose_name_plural': 'Page Sections',
                'ordering': ('page', 'id'),
                'managed': True,
                'unique_together': {('page', 'key')},
            },
        ),
        migrations.CreateModel(
            name='AboutSections',
            fields=[
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesection',),
        ),
        migrations.CreateModel(
            name='ContactSections',
            fields=[
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesection',),
        ),
        migrations.CreateModel(
            name='EventsSections',
            fields=[
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesection',),
        ),
        migrations.CreateModel(
            name='GiveSections',
            fields=[
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesection',),
        ),
        migrations.CreateModel(
            name='HomepageSections',
            fields=[
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesection',),
        ),
        migrations.CreateModel(
            name='PrayerSections',
            fields=[
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesection',),
        ),
        migrations.CreateModel(
            name='SeriesSections',
            fields=[
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesection',),
        ),
        migrations.CreateModel(
            name='SermonsSections',
            fields=[
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesection',),
        ),
        migrations.CreateModel(
            name='VisitSections',
            fields=[
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.sitesection',),
        ),
    ]
