# Generated by Django 5.2.16 on 2026-09-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_sitesection_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIntroConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Welcome, Vision & Mission',
                'verbose_name_plural': 'Welcome, Vision & Mission',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.systemconfig',),
        ),
        migrations.CreateModel(
            name='AboutThemeConfig',
            fields=[
            ],
            options={
                'verbose_name': '2026 Theme',
                'verbose_name_plural': '2026 Theme',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.systemconfig',),
        ),
        migrations.CreateModel(
            name='AboutValuesConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Our Values',
                'verbose_name_plural': 'Our Values',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.systemconfig',),
        ),
    ]
