# Generated by Django 5.2.16 on 2026-09-28 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_aboutintroconfig_aboutthemeconfig_aboutvaluesconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='2026 Theme', max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('scripture', models.CharField(help_text='Scripture reference, e.g. "Zechariah 10:1".', max_length=255)),
                ('scripture_text', models.TextField()),
                ('image', models.CharField(blank=True, help_text='Image path or URL, e.g. /images/posters/theme-2026-latter-rain.jpeg', max_length=512)),
                ('button_label', models.CharField(default='Join Us', max_length=64)),
                ('button_url', models.CharField(default='/visit', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '2026 Theme',
                'verbose_name_plural': '2026 Theme',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AboutValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AboutValuesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Our Values', max_length=128)),
                ('subtitle', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Our Values',
                'verbose_name_plural': 'Our Values',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AboutWelcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='1 Peter 2:9', help_text='Small label above the heading, e.g. a scripture reference.', max_length=128)),
                ('title', models.CharField(default='Welcome to the Embassy', max_length=255)),
                ('vision_label', models.CharField(default='our Vision', help_text='Rendered after an em dash under the vision quote.', max_length=64)),
                ('vision_text', models.TextField()),
                ('mission_label', models.CharField(default='Our Mission', help_text='Rendered after an em dash under the mission quote.', max_length=64)),
                ('mission_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Welcome, Vision & Mission',
                'verbose_name_plural': 'Welcome, Vision & Mission',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.DeleteModel(
            name='AboutIntroConfig',
        ),
        migrations.DeleteModel(
            name='AboutThemeConfig',
        ),
        migrations.DeleteModel(
            name='AboutValuesConfig',
        ),
        migrations.AddField(
            model_name='aboutvalue',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='content.aboutvaluessection'),
        ),
    ]
