# Generated by Django 5.2.16 on 2026-09-29 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_about_seed_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitComingSunday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='I Am Coming This Sunday', max_length=255)),
                ('description', models.TextField(blank=True, default="Questions before you visit? Reach out — we're happy to help.")),
                ('button_label', models.CharField(default='Contact Us', max_length=64)),
                ('button_url', models.CharField(default='#rsvp', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'I Am Coming This Sunday',
                'verbose_name_plural': 'I Am Coming This Sunday',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='VisitExpectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='First Visit?', max_length=128)),
                ('title', models.CharField(default='What to Expect', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'What to Expect',
                'verbose_name_plural': 'What to Expect',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='VisitFaqSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Frequently Asked Questions', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQs',
                'verbose_name_plural': 'FAQs',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='VisitHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="You're Welcome Here", max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Everything you need to know for your first visit to Royal Priesthood Embassy in Thika, Kenya.')),
                ('scripture', models.CharField(blank=True, default='', help_text='Small label above the heading. Leave blank to hide.', max_length=255)),
                ('variant', models.CharField(choices=[('warm', 'Warm'), ('celestial', 'Celestial'), ('parchment', 'Parchment')], default='warm', help_text='Background register. Warm matches the current page.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Hero',
                'verbose_name_plural': 'Page Hero',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='VisitLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Find Us', max_length=128)),
                ('title', models.CharField(default='Visit Us in Thika', max_length=255)),
                ('description', models.TextField(default='We meet at Voice of Grace, behind Spoonzoom in Thika. Look for the hospitality team at the entrance — they will guide you to parking and seating.')),
                ('button_label', models.CharField(default='Get Directions', max_length=64)),
                ('button_url', models.CharField(default='https://maps.app.goo.gl/PLHU6uvwqJHPG9PD6', max_length=512)),
                ('map_embed_url', models.CharField(default='https://maps.google.com/maps?q=Voice+of+Grace+Behind+Spoonzoom+Thika+Kenya&output=embed', help_text='iframe src for the embedded Google map.', max_length=1024)),
                ('map_title', models.CharField(default='Royal Priesthood Embassy location map', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location & Map',
                'verbose_name_plural': 'Location & Map',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='VisitRsvpSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='RSVP for Your Visit', max_length=255)),
                ('subheading', models.TextField(blank=True, default="Let us know you're coming so our hospitality team can greet you personally.")),
                ('submit_label', models.CharField(default='Confirm RSVP', max_length=64)),
                ('success_title', models.CharField(default="You're on the list!", max_length=255)),
                ('success_message', models.TextField(blank=True, default='Our hospitality team has received your RSVP and will prepare a warm welcome for you.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RSVP Form Copy',
                'verbose_name_plural': 'RSVP Form Copy',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='VisitExpectStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(help_text='Card title, e.g. Arrive.', max_length=128)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('music', 'Music (worship note)'), ('book-open', 'Book (teaching)'), ('users', 'Users (community)'), ('trending-up', 'Trending Up (growth)')], default='users', max_length=16)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='content.visitexpectsection')),
            ],
            options={
                'verbose_name': 'Expect Step',
                'verbose_name_plural': 'Expect Steps',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='VisitFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512)),
                ('answer', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='content.visitfaqsection')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
