# Generated by Django 5.2.16 on 2026-09-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_visit_seed_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SermonDetailCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_note', models.CharField(default='Watch this teaching on our YouTube channel', help_text='Note inside the video placeholder.', max_length=255)),
                ('watch_button_label', models.CharField(default='Watch on YouTube', help_text='Primary button label (rendered under the video and in the buttons row).', max_length=64)),
                ('secondary_button_label', models.CharField(default='Kingdom Formation', help_text='Secondary button label next to Watch on YouTube.', max_length=64)),
                ('secondary_button_url', models.CharField(default='/academy', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sermon Detail Copy',
                'verbose_name_plural': 'Sermon Detail Copy',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='SermonsBrowseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Browse by Series', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Browse by Series',
                'verbose_name_plural': 'Browse by Series',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='SermonsGridSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='All Sermons', max_length=255)),
                ('empty_text', models.CharField(default='No sermons available yet.', help_text='Shown when no sermons are published.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'All Sermons',
                'verbose_name_plural': 'All Sermons',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='SermonsHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='/images/Thumbnail_final.jpg', help_text='Banner image path or URL, e.g. /images/Thumbnail_final.jpg', max_length=512)),
                ('image_alt', models.CharField(default='Latest Teaching', max_length=255)),
                ('label', models.CharField(default='Latest sermon', help_text='Large label on the left of the banner.', max_length=64)),
                ('preacher', models.CharField(default='Pst Charles Muchemi', max_length=255)),
                ('title', models.CharField(default='Emotional Intelligence', max_length=255)),
                ('button_label', models.CharField(default='Watch Sermon →', max_length=64)),
                ('button_url', models.CharField(default='/sermons', max_length=512)),
                ('register', models.CharField(choices=[('warm', 'Warm'), ('celestial', 'Celestial'), ('parchment', 'Parchment')], default='celestial', help_text='Background register. Celestial matches the current page.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Hero',
                'verbose_name_plural': 'Page Hero',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='SermonsRelatedSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Related Sermons', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Related Sermons',
                'verbose_name_plural': 'Related Sermons',
                'ordering': ('-updated_at',),
            },
        ),
    ]
