# Generated by Django 5.2.16 on 2026-10-02 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_sermons_seed_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveAllocationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Where Your Giving Goes', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='', help_text='Optional subheading. Leave blank to hide (matches current page).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Where Giving Goes',
                'verbose_name_plural': 'Where Giving Goes',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='GiveHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Give', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Your generosity fuels community outreach, global missions, and the daily work of the Kingdom Embassy.')),
                ('scripture', models.CharField(blank=True, default='2 Corinthians 9:7', help_text='Small label above the heading. Leave blank to hide.', max_length=255)),
                ('register', models.CharField(choices=[('warm', 'Warm'), ('celestial', 'Celestial'), ('parchment', 'Parchment')], default='warm', help_text='Background register. Warm matches the current page.', max_length=16)),
                ('image', models.CharField(blank=True, default='', help_text='Optional banner image path or URL. Leave blank for no image.', max_length=512)),
                ('image_alt', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Hero',
                'verbose_name_plural': 'Page Hero',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='GiveMpesaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='M-Pesa Giving', max_length=128)),
                ('till_number', models.CharField(default='8598004', help_text='M-Pesa Till number shown in large type.', max_length=32)),
                ('till_caption', models.CharField(default='Till Number', max_length=64)),
                ('account_name', models.CharField(default='Salome Njuguna Waruguru', max_length=255)),
                ('instructions', models.TextField(blank=True, default='Go to M-Pesa → Lipa na M-Pesa → Buy Goods and Services → Enter Till Number')),
                ('button_label', models.CharField(default='Need Help Giving?', max_length=64)),
                ('button_url', models.CharField(default='/contact', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'M-Pesa Giving',
                'verbose_name_plural': 'M-Pesa Giving',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='GiveWhySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, default='', help_text='Small label above the heading. Leave blank to hide.', max_length=128)),
                ('heading', models.CharField(blank=True, default='', help_text='Section heading. Leave blank to hide.', max_length=255)),
                ('body', models.TextField(default='We give because God first gave — generously, sacrificially, and with joy. Your giving is an act of worship and partnership in advancing the Gospel. Every contribution, whether large or small, makes a Kingdom impact in Thika and beyond.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why We Give',
                'verbose_name_plural': 'Why We Give',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='GiveAllocationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Card title, e.g. Community Programs.', max_length=128)),
                ('percentage', models.CharField(blank=True, default='', help_text='Share label, e.g. 35%. Leave blank to hide.', max_length=16)),
                ('description', models.TextField()),
                ('image', models.CharField(blank=True, default='', help_text='Optional card image path or URL. Leave blank for no image.', max_length=512)),
                ('image_alt', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.giveallocationsection')),
            ],
            options={
                'verbose_name': 'Allocation Item',
                'verbose_name_plural': 'Allocation Items',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
