# Generated by Django 5.2.16 on 2026-10-06 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_give_seed_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetailsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_heading', models.CharField(default='Email', max_length=64)),
                ('email_address', models.CharField(blank=True, default='', help_text='Contact email. Leave blank to use the site default.', max_length=255)),
                ('location_heading', models.CharField(default='Location', max_length=64)),
                ('street', models.CharField(blank=True, default='', help_text='Street line. Leave blank to use the site default.', max_length=255)),
                ('city', models.CharField(blank=True, default='', help_text='City. Leave blank to use the site default.', max_length=128)),
                ('country', models.CharField(blank=True, default='', help_text='Country. Leave blank to use the site default.', max_length=128)),
                ('maps_url', models.CharField(blank=True, default='', help_text='Get Directions URL. Leave blank to use the site default.', max_length=512)),
                ('directions_label', models.CharField(default='Get Directions →', max_length=64)),
                ('social_heading', models.CharField(default='Social Media', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Details',
                'verbose_name_plural': 'Contact Details',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ContactFormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Send a Message', max_length=255)),
                ('name_label', models.CharField(default='Name', max_length=64)),
                ('email_label', models.CharField(default='Email', max_length=64)),
                ('phone_label', models.CharField(default='Phone (optional)', max_length=64)),
                ('message_label', models.CharField(default='Message', max_length=64)),
                ('submit_label', models.CharField(default='Send Message', max_length=64)),
                ('sending_label', models.CharField(default='Sending…', max_length=64)),
                ('success_message', models.TextField(default="Message sent! We'll be in touch soon.")),
                ('error_message', models.TextField(default='Something went wrong. Please email us directly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Form',
                'verbose_name_plural': 'Contact Form',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ContactHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Us', max_length=255)),
                ('subtitle', models.TextField(blank=True, default="We'd love to hear from you. Reach out with questions, prayer requests, or to plan your visit.")),
                ('scripture', models.CharField(blank=True, default='', help_text='Small label above the heading. Leave blank to hide.', max_length=255)),
                ('register', models.CharField(choices=[('warm', 'Warm'), ('celestial', 'Celestial'), ('parchment', 'Parchment')], default='parchment', help_text='Background register. Parchment matches the current page.', max_length=16)),
                ('image', models.CharField(blank=True, default='', help_text='Optional banner image path or URL. Leave blank for no image.', max_length=512)),
                ('image_alt', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Hero',
                'verbose_name_plural': 'Page Hero',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='ContactSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(help_text='Network key, e.g. instagram, facebook, youtube.', max_length=64)),
                ('label', models.CharField(blank=True, default='', help_text='Display label. Leave blank to use the capitalized network.', max_length=64)),
                ('url', models.CharField(max_length=512)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='content.contactdetailssection')),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ('sort_order', 'id'),
            },
        ),
    ]
