# Generated by Django 5.2.16 on 2026-07-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0003_alter_prayersubmission_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='prayersubmission',
            index=models.Index(fields=['created_at'], name='prayer_created_idx'),
        ),
    ]
