"""Convert TEXT primary key columns to UUID type for Prisma-legacy tables.

All existing UUID values stored as TEXT have been validated as valid UUIDs.
This migration alters the column types to match Django model declarations.

Generated by manual audit (B4.2.4). Not auto-generated by makemigrations.
"""

from django.db import migrations


class Migration(migrations.Migration):
    """Convert TEXT id columns to UUID for Prisma-legacy tables in prayer app."""

    dependencies = [
        ('prayer', '0004_prayersubmission_prayer_created_idx'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE "PrayerSubmission" ALTER COLUMN id TYPE uuid USING id::uuid;
            """,
            reverse_sql="""
            ALTER TABLE "PrayerSubmission" ALTER COLUMN id TYPE text;
            """,
            state_operations=None,
        ),
    ]