/** Canonical image paths — maps rpweb source assets to website usage. */
export const images = {
  hero: "/images/services/kingdom-formation-1.jpg",
  theme2026: "/images/posters/theme-2026-latter-rain.jpeg",
  theme2026Gallery: [
    "/images/services/rain-of-mercy-1.jpg",
    "/images/services/rain-of-mercy-2.jpg",
    "/images/services/rain-of-mercy-3.jpg",
    "/images/services/rain-of-mercy-4.jpg",
    "/images/services/rain-of-mercy-5.jpg",
    "/images/services/rain-of-mercy-7.jpg",
  ],
  sundayOnlinePoster: "/images/events/sunday-online-service-poster-1.jpeg",
  sundayOnlinePosterAlt: "/images/events/sunday-online-service-poster-2.jpeg",
  kingdomFormationPoster: "/images/events/kingdom-formation-poster.jpeg",
  sundayMainWorship: "/images/services/kingdom-formation-2.jpg",
  youthWorship: "/images/services/kingdom-formation-4.jpg",
  communityFellowship: "/images/services/kingdom-formation-6.jpg",
  visitWelcome: "/images/services/kingdom-formation-3.jpg",
  events: {
    evangelism: "/images/events/evangelism-poster-2026.jpeg",
    praiseOutburst: "/images/events/praise-outburst-2026-poster.jpeg",
    bethelExperience: "/images/events/bethel-experience-2026.jpeg",
    cookout: "/images/events/cookout-poster-2026.jpeg",
    movieNight: "/images/events/movie-night-2026.jpeg",
  },
  academyHero: "/images/events/kingdom-formation-poster.jpeg",
  series: {
    "fruit-of-spirit": "/images/services/kingdom-formation-12.jpg",
    foundations: "/images/services/kingdom-formation-6.jpg",
    "nature-of-priesthood": "/images/services/kingdom-formation-8.jpg",
    "finished-work": "/images/services/kingdom-formation-10.jpg",
    "sonship-identity": "/images/services/kingdom-formation-1.jpg",
    "morning-devotionals": "/images/services/rain-of-mercy-3.jpg",
    "gift-series": "/images/services/kingdom-formation-14-.jpg",
    "worship-devotion": "/images/services/kingdom-formation-15.jpg",
  },
  team: {
    "charles-muchemi": "/images/team/charles-muchemi.jpg",
    "mark-mwangi": "/images/team/mark-mwangi.jpg",
    "salome-waruguru": "/images/team/salome-waruguru.jpg",
    "lucy-auma": "/images/team/lucy-auma.jpg",
    "mercy-zawadi": "/images/team/mercy-zawadi.jpg",
    "mary-wamuyu": "/images/team/mary-wamuyu.jpg",
    "gloria-kimaru": "/images/team/gloria-kimaru.jpg",
  },
} as const;